name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        # with: swift-version: "5.7"  // XCode 14.1

      - name: Install Mint
        run: brew install mint

      - name: Mint Setup
        run: mint bootstrap

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'

      - name: UnitTests
        run: xcodebuild test -scheme UnitTests -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 12,OS=16.1'
        
      - name: UITests
        run: xcodebuild test -scheme UITests -sdk iphonesimulator -destination platform='iOS Simulator,name=iPhone 12,OS=16.1'
